 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: 
   - 'build' 
   - '-t' 
   - 'gcr.io/$PROJECT_ID/storage:$COMMIT_SHA'
   - '.'
   - '--file=./service.dockerfile'
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/storage:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'storage'
   - '--image'
   - 'gcr.io/$PROJECT_ID/storage:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated'
 images:
 - 'gcr.io/$PROJECT_ID/storage:$COMMIT_SHA'
